language: go

go:
  - tip
  
install:
  - go get github.com/PuerkitoBio/goquery
  - go get github.com/headzoo/ut
  
script:
 - go test -v ./...
 
notifications:
  email:
    - vaskovasilev94@yahoo.com
    